# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/k1g99/"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "mail"
# name = "Mail"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
